### ISSUE TITLE
Cannot run tests on cloned project

### ISSUE THREAD

**Issue by oleg-py** [scalalandio/catnip#6]
Hello. I cloned the project and tried to run tests on `catnipTestsJVM` subproject and got this error. Tried on Mac and Windows machines that I have:
```
[error] java.lang.NoClassDefFoundError: Could not initialize class io.scalaland.catnip.internals.DerivedImpl$
[error]         at io.scalaland.catnip.Semi$.impl(Semi.scala:17)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$4(JavaReflectionRuntimes.scala:34)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:803)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime$(Macros.scala:779)
[error]         at scala.tools.nsc.Global$$anon$1.macroExpandWithRuntime(Global.scala:448)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:620)
[error]         at scala.tools.nsc.Global.withInfoLevel(Global.scala:219)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:613)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:600)
[error]         at org.scalamacros.paradise.typechecker.Expanders$Expander.expand$1(Expanders.scala:64)
[error]         at org.scalamacros.paradise.typechecker.Expanders$Expander.$anonfun$expandAnnotationMacro$2(Expanders.scala:121)
[error]         at org.scalamacros.paradise.typechecker.Expanders$Expander.onlyIfExpansionAllowed$1(Expanders.scala:58)
[error]         at org.scalamacros.paradise.typechecker.Expanders$Expander.expandAnnotationMacro(Expanders.scala:121)
[error]         at org.scalamacros.paradise.typechecker.Expanders$Expander.expandAnnotationMacro$(Expanders.scala:32)
[error]         at org.scalamacros.paradise.typechecker.Namers$$anon$3.expandAnnotationMacro(Namers.scala:13)
[error]         at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.maybeExpand$1(Namers.scala:371)
[error]         at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.$anonfun$maybeExpand$2(Namers.scala:383)
[error]         at scala.collection.immutable.Stream.flatMap(Stream.scala:486)
[error]         at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.maybeExpand(Namers.scala:383)
[error]         at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:333)
[error]         at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:323)
[error]         at org.scalamacros.paradise.typechecker.Namers$Namer$RichType.completeOnlyExpansions(Namers.scala:351)
[error]         at org.scalamacros.paradise.typechecker.Expanders$Expander.$anonfun$expandMacroAnnotations$2(Expanders.scala:148)
[error]         at scala.collection.immutable.List.flatMap(List.scala:335)
[error]         at org.scalamacros.paradise.typechecker.Expanders$Expander.expandMacroAnnotations(Expanders.scala:141)
[error]         at org.scalamacros.paradise.typechecker.Expanders$Expander.expandMacroAnnotations$(Expanders.scala:128)
[error]         at org.scalamacros.paradise.typechecker.Expanders$$anon$1.expandMacroAnnotations(Expanders.scala:14)
[error]         at org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$.pluginsEnterStats(AnalyzerPlugins.scala:33)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.$anonfun$pluginsEnterStats$1(AnalyzerPlugins.scala:482)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterStats(AnalyzerPlugins.scala:481)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterStats$(AnalyzerPlugins.scala:478)
[error]         at scala.tools.nsc.Global$$anon$1.pluginsEnterStats(Global.scala:448)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2422)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$97(Typers.scala:5561)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:486)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5596)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3290)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:477)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArg0$1(Typers.scala:3433)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$14(Typers.scala:3453)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$13(Typers.scala:3423)
[error]         at scala.tools.nsc.typechecker.Contexts$Context.$anonfun$savingUndeterminedTypeParams$1(Contexts.scala:328)
[error]         at scala.tools.nsc.typechecker.Contexts$Context.savingUndeterminedTypeParams(Contexts.scala:392)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.handleOverloaded$1(Typers.scala:3420)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3464)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$25(Typers.scala:4687)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$silent$2(Typers.scala:714)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:714)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4687)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4771)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4801)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5586)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2475)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$97(Typers.scala:5561)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:486)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5596)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3290)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:477)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArg0$1(Typers.scala:3433)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$14(Typers.scala:3453)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$13(Typers.scala:3423)
[error]         at scala.tools.nsc.typechecker.Contexts$Context.$anonfun$savingUndeterminedTypeParams$1(Contexts.scala:328)
[error]         at scala.tools.nsc.typechecker.Contexts$Context.savingUndeterminedTypeParams(Contexts.scala:392)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.handleOverloaded$1(Typers.scala:3420)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3464)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$25(Typers.scala:4687)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:700)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4687)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4771)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4801)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5586)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5603)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2006)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1829)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5552)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5602)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5262)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5555)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5602)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5699)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:104)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:944)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1533)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1507)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by MateuszKubuszok** [comment]
Thanks for the report!

I managed to reproduce the issue in Docker on Debian to make sure I have a clean situation with no artifacts, cache etc.

This error you get when macro cannot find `derive.semi.conf`. I added [a branch](https://github.com/scalalandio/catnip/tree/git-clone-failing-fix) which you can use to confirm if this is the same error you have.

It appears that inside `modules/catnip/.jvm/target/scala-2.12/classes` resource `derive.semi.conf` is not copied from `modules/catnip/.jvm/resources`. Why is it not copied? Because there is not such folder.

Thing is, sbt-cross-project doesn't allow you to share resources, only source code. I worked around it using symlinks- newer versions of git respect then and will recreate them on checkout. This is probably why it work on my computer (Arch Linux, git 2.19.0) but fails in repo environment (Debian, git 2.11.0). I wasn't aware how new this feature is, so I need to rethink my workaround...

Could you help mi figure if that is the issue you see? Basically check if `modules/.jvm` and `modules/.js` are missing `resources` directory and that once you add symlink it compiles again.

**Comment by oleg-py** [comment]
@MateuszKubuszok yeah, the resources is missing. After switching branches I have a symlink pointing to

```/home/dev/Workspaces/scalaland.io/catnip/modules/catnip/src/main/resources```


So it's not working (on Windows :). I'll see if I can make it work on my machine, thanks.

**Comment by MateuszKubuszok** [comment]
@oleg-py, thanks! Ah, Windows :)

If I won't be able to figure anything better I will replace symlinks with copies. Though I would really prefer that sbt-cross-project supported resource sharing.

**Comment by MateuszKubuszok** [comment]
@oleg-py can you take a look if https://github.com/scalalandio/catnip/pull/8 fixes the problem for you?
